version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mp-covenants-term-search-basic"
s3_bucket = "covenants-deed-images"
s3_prefix = "mp-covenants-term-search-basic"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
